<?php

use yii\db\Migration;

class m171212_130621__personinfo extends Migration
{
    public function up()
    {
        /* 取消外键约束 */
        $this->execute('SET foreign_key_checks = 0');
        
        /* 创建表 */
        $this->createTable('{{%_personinfo}}', [
            'id' => "varchar(32) NOT NULL",
            'original_id' => "int(11) NULL",
            'name' => "varchar(64) NOT NULL",
            'namepinyin' => "varchar(128) NULL",
            'sex' => "enum('男','女') NOT NULL",
            'is_married' => "enum('是','否') NOT NULL",
            'spouse_type' => "varchar(24) NULL",
            'property' => "enum('党员','团员','群众') NULL",
            'photo' => "varchar(64) NULL",
            'can_home_weekend' => "enum('是','否') NOT NULL",
            'birthdate' => "date NOT NULL",
            'armydate' => "date NOT NULL",
            'current_mil_rank_date' => "date NULL",
            'next_mil_rank_date' => "date NULL",
            'current_techgrade_date' => "date NULL",
            'next_techgrade_date' => "date NULL",
            'current_other_date' => "date NULL",
            'next_other_date' => "date NULL",
            'status' => "int(2) NOT NULL DEFAULT '0'",
            'mil_rank' => "int(2) NOT NULL",
            'unit_code' => "int(11) NOT NULL",
            'tech_grade' => "varchar(32) NULL",
            'job' => "varchar(32) NOT NULL",
            'tel' => "varchar(32) NULL",
            'myhome_province' => "int(4) NULL",
            'myhome_city' => "int(4) NULL",
            'myhome_district' => "int(4) NULL",
            'parentshome_province' => "int(4) NULL",
            'parentshome_city' => "int(4) NULL",
            'parentshome_district' => "int(4) NULL",
            'hometown' => "varchar(56) NULL",
            'qrcode' => "varchar(256) NULL",
            'minzu' => "varchar(24) NULL",
            'education' => "varchar(18) NULL",
            'armyaddress' => "varchar(32) NULL",
            'type_date' => "date NULL",
            'current_job_date' => "date NULL",
            'home_address' => "varchar(128) NULL",
            'ps' => "varchar(128) NULL",
            'PRIMARY KEY (`id`)'
        ], "ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='个人信息表'");
        
        /* 索引设置 */
        
        
        /* 表数据 */
        $this->insert('{{%_personinfo}}',['id'=>'caocao.6@winter.com','original_id'=>NULL,'name'=>'曹操','namepinyin'=>'caocao','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>'','can_home_weekend'=>'是','birthdate'=>'1985-04-03','armydate'=>'2011-07-02','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'3','mil_rank'=>'12','unit_code'=>'7','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'28','parentshome_city'=>'301','parentshome_district'=>'2753','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'guanyu.6@winter.com','original_id'=>NULL,'name'=>'关羽','namepinyin'=>'guanyu','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-01','armydate'=>'2011-06-30','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'7','mil_rank'=>'12','unit_code'=>'6','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'hepengfei.1.201201@winter.com','original_id'=>NULL,'name'=>'贺鹏飞','namepinyin'=>'hepengfei','sex'=>'男','is_married'=>'是','spouse_type'=>NULL,'property'=>'党员','photo'=>'','can_home_weekend'=>'是','birthdate'=>'2012-01-01','armydate'=>'2012-01-01','current_mil_rank_date'=>'2012-01-01','next_mil_rank_date'=>'2012-01-01','current_techgrade_date'=>'2012-01-01','next_techgrade_date'=>'2012-01-01','current_other_date'=>'2012-01-01','next_other_date'=>'2012-01-01','status'=>'13','mil_rank'=>'12','unit_code'=>'12','tech_grade'=>'2012-01-01','job'=>'qwe','tel'=>'qweqwe','myhome_province'=>'12','myhome_city'=>'105','myhome_district'=>'1015','parentshome_province'=>'12','parentshome_city'=>'105','parentshome_district'=>'1015','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'hepengfei.13.201610@winter.com','original_id'=>NULL,'name'=>'贺鹏飞','namepinyin'=>'hepengfei','sex'=>'男','is_married'=>'是','spouse_type'=>NULL,'property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'2016-10-17','armydate'=>'2016-10-17','current_mil_rank_date'=>'2016-10-17','next_mil_rank_date'=>'2016-10-17','current_techgrade_date'=>'2016-10-17','next_techgrade_date'=>'2016-10-17','current_other_date'=>'2016-10-17','next_other_date'=>'2016-10-17','status'=>'13','mil_rank'=>'12','unit_code'=>'13','tech_grade'=>'122','job'=>'123','tel'=>'1232','myhome_province'=>NULL,'myhome_city'=>NULL,'myhome_district'=>NULL,'parentshome_province'=>NULL,'parentshome_city'=>NULL,'parentshome_district'=>NULL,'hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'hepengfei.3.199001@winter.com','original_id'=>NULL,'name'=>'贺鹏飞','namepinyin'=>'hepengfei','sex'=>'男','is_married'=>'否','spouse_type'=>'随队','property'=>'群众','photo'=>'','can_home_weekend'=>'是','birthdate'=>'1990-01-01','armydate'=>'2011-06-30','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'13','mil_rank'=>'12','unit_code'=>'3','tech_grade'=>'五级','job'=>'干活的','tel'=>'13423','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>'某省某县','qrcode'=>NULL,'minzu'=>'汉','education'=>'小学','armyaddress'=>'不知道','type_date'=>'2013-06-02','current_job_date'=>'2015-01-01','home_address'=>'某山某水某地方','ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'hepengfei1.3.199001@winter.com','original_id'=>NULL,'name'=>'贺鹏飞','namepinyin'=>'hepengfei1','sex'=>'男','is_married'=>'否','spouse_type'=>'随队','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-01','armydate'=>'2011-06-30','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'12','unit_code'=>'3','tech_grade'=>'五级','job'=>'干活的','tel'=>'135','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>'某省某县','qrcode'=>NULL,'minzu'=>'汉','education'=>'小学','armyaddress'=>'不知道','type_date'=>'2013-06-03','current_job_date'=>'2015-01-01','home_address'=>'某山某水某地方','ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'hepengfei2.3.199001@winter.com','original_id'=>NULL,'name'=>'贺鹏飞','namepinyin'=>'hepengfei2','sex'=>'男','is_married'=>'否','spouse_type'=>'随队','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-01','armydate'=>'2011-06-30','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'12','unit_code'=>'3','tech_grade'=>'五级','job'=>'干活的','tel'=>'136','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>'某省某县','qrcode'=>NULL,'minzu'=>'汉','education'=>'小学','armyaddress'=>'不知道','type_date'=>'2013-06-04','current_job_date'=>'2015-01-01','home_address'=>'某山某水某地方','ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'hepengfei3.3.199001@winter.com','original_id'=>NULL,'name'=>'贺鹏飞','namepinyin'=>'hepengfei3','sex'=>'男','is_married'=>'否','spouse_type'=>NULL,'property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-01','armydate'=>'2011-06-30','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'12','unit_code'=>'3','tech_grade'=>'五级','job'=>'干活的','tel'=>'137','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>'某省某县','qrcode'=>NULL,'minzu'=>'汉','education'=>'小学','armyaddress'=>'不知道','type_date'=>'2013-06-05','current_job_date'=>'2015-01-01','home_address'=>'某山某水某地方','ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'liqingzhao.6@winter.com','original_id'=>NULL,'name'=>'李清照','namepinyin'=>'liqingzhao','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-03','armydate'=>'2011-07-03','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'4','mil_rank'=>'12','unit_code'=>'13','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'litianci.3.199001@winter.com','original_id'=>NULL,'name'=>'李天赐','namepinyin'=>'litianci','sex'=>'男','is_married'=>'否','spouse_type'=>'随军','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-01','armydate'=>'2011-06-30','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'12','unit_code'=>'3','tech_grade'=>'五级','job'=>'干活的','tel'=>'133','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1048','parentshome_province'=>'12','parentshome_city'=>'109','parentshome_district'=>'1048','hometown'=>'某省某县','qrcode'=>NULL,'minzu'=>'汉','education'=>'小学','armyaddress'=>'不知道','type_date'=>'2013-06-01','current_job_date'=>'2015-01-01','home_address'=>'某山某水某地方','ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong11.14@winter.com','original_id'=>NULL,'name'=>'孙悟空11','namepinyin'=>'sunwukong11','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-14','armydate'=>'2011-07-14','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'5','unit_code'=>'14','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong12.14@winter.com','original_id'=>NULL,'name'=>'孙悟空12','namepinyin'=>'sunwukong12','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-15','armydate'=>'2011-07-15','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'5','unit_code'=>'14','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong13.14@winter.com','original_id'=>NULL,'name'=>'孙悟空13','namepinyin'=>'sunwukong13','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-16','armydate'=>'2011-07-16','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'2','unit_code'=>'14','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong14.14@winter.com','original_id'=>NULL,'name'=>'孙悟空14','namepinyin'=>'sunwukong14','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-17','armydate'=>'2011-07-17','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'2','unit_code'=>'14','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong15.14@winter.com','original_id'=>NULL,'name'=>'孙悟空15','namepinyin'=>'sunwukong15','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-18','armydate'=>'2011-07-18','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'2','unit_code'=>'14','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong16.15@winter.com','original_id'=>NULL,'name'=>'孙悟空16','namepinyin'=>'sunwukong16','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-19','armydate'=>'2011-07-19','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'2','unit_code'=>'15','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong17.15@winter.com','original_id'=>NULL,'name'=>'孙悟空17','namepinyin'=>'sunwukong17','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-20','armydate'=>'2011-07-20','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'2','unit_code'=>'15','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong18.15@winter.com','original_id'=>NULL,'name'=>'孙悟空18','namepinyin'=>'sunwukong18','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-21','armydate'=>'2011-07-21','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'2','unit_code'=>'15','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong19.15@winter.com','original_id'=>NULL,'name'=>'孙悟空19','namepinyin'=>'sunwukong19','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-22','armydate'=>'2011-07-22','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'13','unit_code'=>'15','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong2.12@winter.com','original_id'=>NULL,'name'=>'孙悟空2','namepinyin'=>'sunwukong2','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-05','armydate'=>'2011-07-05','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'1','unit_code'=>'12','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong20.15@winter.com','original_id'=>NULL,'name'=>'孙悟空20','namepinyin'=>'sunwukong20','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-23','armydate'=>'2011-07-23','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'13','unit_code'=>'15','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong21.15@winter.com','original_id'=>NULL,'name'=>'孙悟空21','namepinyin'=>'sunwukong21','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-24','armydate'=>'2011-07-24','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'13','unit_code'=>'15','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong22.15@winter.com','original_id'=>NULL,'name'=>'孙悟空22','namepinyin'=>'sunwukong22','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-25','armydate'=>'2011-07-25','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'15','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong23.15@winter.com','original_id'=>NULL,'name'=>'孙悟空23','namepinyin'=>'sunwukong23','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-26','armydate'=>'2011-07-26','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'15','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong24.5@winter.com','original_id'=>NULL,'name'=>'孙悟空24','namepinyin'=>'sunwukong24','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-27','armydate'=>'2011-07-27','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'5','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong25.5@winter.com','original_id'=>NULL,'name'=>'孙悟空25','namepinyin'=>'sunwukong25','sex'=>'女','is_married'=>'是','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-28','armydate'=>'2011-07-28','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'5','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong26.5@winter.com','original_id'=>NULL,'name'=>'孙悟空26','namepinyin'=>'sunwukong26','sex'=>'女','is_married'=>'是','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-29','armydate'=>'2011-07-29','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'5','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong27.4@winter.com','original_id'=>NULL,'name'=>'孙悟空27','namepinyin'=>'sunwukong27','sex'=>'女','is_married'=>'是','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-30','armydate'=>'2011-07-30','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'4','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong28.4@winter.com','original_id'=>NULL,'name'=>'孙悟空28','namepinyin'=>'sunwukong28','sex'=>'女','is_married'=>'是','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-31','armydate'=>'2011-07-31','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'4','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong29.4@winter.com','original_id'=>NULL,'name'=>'孙悟空29','namepinyin'=>'sunwukong29','sex'=>'女','is_married'=>'是','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-01','armydate'=>'2011-08-01','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'4','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong3.12@winter.com','original_id'=>NULL,'name'=>'孙悟空3','namepinyin'=>'sunwukong3','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-06','armydate'=>'2011-07-06','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'11','mil_rank'=>'1','unit_code'=>'12','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong30.4@winter.com','original_id'=>NULL,'name'=>'孙悟空30','namepinyin'=>'sunwukong30','sex'=>'女','is_married'=>'是','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-02','armydate'=>'2011-08-02','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'4','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong31.8@winter.com','original_id'=>NULL,'name'=>'孙悟空31','namepinyin'=>'sunwukong31','sex'=>'女','is_married'=>'是','spouse_type'=>'是','property'=>'党员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-03','armydate'=>'2011-08-03','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'8','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong32.8@winter.com','original_id'=>NULL,'name'=>'孙悟空32','namepinyin'=>'sunwukong32','sex'=>'男','is_married'=>'是','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-04','armydate'=>'2011-08-04','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'1','mil_rank'=>'13','unit_code'=>'7','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong33.8@winter.com','original_id'=>NULL,'name'=>'孙悟空33','namepinyin'=>'sunwukong33','sex'=>'男','is_married'=>'是','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-05','armydate'=>'2011-08-05','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'1','mil_rank'=>'13','unit_code'=>'7','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong34.8@winter.com','original_id'=>NULL,'name'=>'孙悟空34','namepinyin'=>'sunwukong34','sex'=>'男','is_married'=>'是','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-06','armydate'=>'2011-08-06','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'1','mil_rank'=>'13','unit_code'=>'10','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong35.8@winter.com','original_id'=>NULL,'name'=>'孙悟空35','namepinyin'=>'sunwukong35','sex'=>'男','is_married'=>'是','spouse_type'=>'是','property'=>'团员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-07','armydate'=>'2011-08-07','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'1','mil_rank'=>'13','unit_code'=>'10','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong36.8@winter.com','original_id'=>NULL,'name'=>'孙悟空36','namepinyin'=>'sunwukong36','sex'=>'男','is_married'=>'是','spouse_type'=>'是','property'=>'团员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-08','armydate'=>'2011-08-08','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'1','mil_rank'=>'13','unit_code'=>'10','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong37.9@winter.com','original_id'=>NULL,'name'=>'孙悟空37','namepinyin'=>'sunwukong37','sex'=>'男','is_married'=>'是','spouse_type'=>'是','property'=>'团员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-09','armydate'=>'2011-08-09','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'9','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong38.9@winter.com','original_id'=>NULL,'name'=>'孙悟空38','namepinyin'=>'sunwukong38','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'团员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-10','armydate'=>'2011-08-10','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'9','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong39.9@winter.com','original_id'=>NULL,'name'=>'孙悟空39','namepinyin'=>'sunwukong39','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'团员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-11','armydate'=>'2011-08-11','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'9','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong4.12@winter.com','original_id'=>NULL,'name'=>'孙悟空4','namepinyin'=>'sunwukong4','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-07','armydate'=>'2011-07-07','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'1','unit_code'=>'12','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong40.9@winter.com','original_id'=>NULL,'name'=>'孙悟空40','namepinyin'=>'sunwukong40','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'团员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-12','armydate'=>'2011-08-12','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'9','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong41.9@winter.com','original_id'=>NULL,'name'=>'孙悟空41','namepinyin'=>'sunwukong41','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'团员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-13','armydate'=>'2011-08-13','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'9','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong42.9@winter.com','original_id'=>NULL,'name'=>'孙悟空42','namepinyin'=>'sunwukong42','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'团员','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-14','armydate'=>'2011-08-14','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'9','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong43.9@winter.com','original_id'=>NULL,'name'=>'孙悟空43','namepinyin'=>'sunwukong43','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-15','armydate'=>'2011-08-15','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'9','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong44.16@winter.com','original_id'=>NULL,'name'=>'孙悟空44','namepinyin'=>'sunwukong44','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-02-16','armydate'=>'2011-08-16','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'16','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong45.16@winter.com','original_id'=>NULL,'name'=>'孙悟空45','namepinyin'=>'sunwukong45','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1988-04-04','armydate'=>'2011-08-17','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'13','unit_code'=>'16','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong5.12@winter.com','original_id'=>NULL,'name'=>'孙悟空5','namepinyin'=>'sunwukong5','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-08','armydate'=>'2011-07-08','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'1','unit_code'=>'12','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong6.13@winter.com','original_id'=>NULL,'name'=>'孙悟空6','namepinyin'=>'sunwukong6','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-09','armydate'=>'2011-07-09','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'1','unit_code'=>'13','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong7.13@winter.com','original_id'=>NULL,'name'=>'孙悟空7','namepinyin'=>'sunwukong7','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-10','armydate'=>'2011-07-10','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'1','unit_code'=>'13','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong8.13@winter.com','original_id'=>NULL,'name'=>'孙悟空8','namepinyin'=>'sunwukong8','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-11','armydate'=>'2011-07-11','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'1','unit_code'=>'13','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'sunwukong9.13@winter.com','original_id'=>NULL,'name'=>'孙悟空9','namepinyin'=>'sunwukong9','sex'=>'女','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'否','birthdate'=>'1990-01-12','armydate'=>'2011-07-12','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'0','mil_rank'=>'1','unit_code'=>'13','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        $this->insert('{{%_personinfo}}',['id'=>'zhangfei.6@winter.com','original_id'=>NULL,'name'=>'张飞','namepinyin'=>'zhangfei','sex'=>'男','is_married'=>'否','spouse_type'=>'是','property'=>'群众','photo'=>NULL,'can_home_weekend'=>'是','birthdate'=>'1990-01-01','armydate'=>'2011-07-01','current_mil_rank_date'=>'2013-06-01','next_mil_rank_date'=>'2017-06-01','current_techgrade_date'=>'2015-01-01','next_techgrade_date'=>'2018-01-01','current_other_date'=>NULL,'next_other_date'=>NULL,'status'=>'2','mil_rank'=>'12','unit_code'=>'6','tech_grade'=>'五级','job'=>'干活的','tel'=>'18817559557\'','myhome_province'=>'12','myhome_city'=>'109','myhome_district'=>'1049','parentshome_province'=>'23','parentshome_city'=>'247','parentshome_district'=>'2244','hometown'=>NULL,'qrcode'=>NULL,'minzu'=>NULL,'education'=>NULL,'armyaddress'=>NULL,'type_date'=>NULL,'current_job_date'=>NULL,'home_address'=>NULL,'ps'=>NULL]);
        
        /* 设置外键约束 */
        $this->execute('SET foreign_key_checks = 1;');
    }

    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        /* 删除表 */
        $this->dropTable('{{%_personinfo}}');
        $this->execute('SET foreign_key_checks = 1;');
    }
}

